### ISSUE TITLE
Feature request: Alphabetically sort mods

### ISSUE THREAD

**Issue by Rycia** [affederaffe/BeatSaberModManager#13]
![image](https://user-images.githubusercontent.com/43384589/211120376-54ccae37-6b49-4969-98d8-8f5cabb842f8.png)
I noticed that mods aren't alphabetically ordered in their own sections, can they be alphabetically ordered?

**Comment by affederaffe** [comment]
Done with https://github.com/affederaffe/BeatSaberModManager/commit/b25e4f6d979d46f0658cf916b8b9ccabc232abf7.
