### ISSUE TITLE
Feature Request: Rename "Refresh Mods"

### ISSUE THREAD

**Issue by Rycia** [affederaffe/BeatSaberModManager#14]
I believe "Refresh Mods" on the mods tab looks a bit confusing, so rename it to "Install Mods" or "Injects Mods" or "Update Mods" or "Update Installation" or something.

**Comment by affederaffe** [comment]
Done with https://github.com/affederaffe/BeatSaberModManager/commit/48890f32ebef0b24188a6a576db7571da8223124.
