### ISSUE TITLE
(Linux) No licenses

### ISSUE THREAD

**Issue by TYTheBeast** [affederaffe/BeatSaberModManager#32]
Any way to not use Steam? I've already paid for the game on Quest and don't intend to buy it again on Steam

**Comment by affederaffe** [comment]
Hello, unfortunately your Beat Saber license is bound to the platform and account you bought it on.
If you want to run modded Beat Saber on Linux, you'd have to buy it again on Steam.
Otherwise, checkout [Quest Modding](https://bsmg.wiki/quest-modding.html).
