### ISSUE TITLE
[Feature Request] Installation Path arguement string

### ISSUE THREAD

**Issue by RiskiVR** [affederaffe/BeatSaberModManager#4]
Is it possible for you to add an argument for launching the mod manager w/ the ability to add a launch parameter,  like BeatSaberModManager.exe --path "/Beat Saber path"? This would be very useful.

**Comment by affederaffe** [comment]
Besides the auto-detection, you can already manually set your installation directory in the settings tab. What are the use-cases for this?

**Comment by RiskiVR** [comment]
I'm wanting to have my beat saber launcher call your application, and automatically set it's installed path to which ever one my launcher is set to.
